image:
  file: .gitpod.Dockerfile

tasks:
  - command: sbt --client exit

vscode:
  extensions:
    - scala-lang.scala@0.5.0:3FIiaU1vnooQsX3PkBlBvQ==
    - scalameta.metals@1.10.0:wOYpsld/e93zZ250A0uKHA==

ports:
  - port: 8212
    onOpen: ignore