name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        scala-version: [ "2.12", "2.13", "3" ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          check-latest: true

      - uses: sbt/setup-sbt@v1

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Compile and test
        run: sbt "project root2_12; scalafixAll --check; test"
        if: matrix.scala-version == '2.12'

      - name: Compile and test
        run: sbt "project root; scalafixAll --check; test"
        if: matrix.scala-version == '2.13'

      - name: Compile and test
        run: sbt "project root3; scalafixAll --check; test"
        if: matrix.scala-version == '3'

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          check-latest: true

      - uses: sbt/setup-sbt@v1

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Publish artifacts
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: sbt ci-release

  ci-passed:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - run: ':'
