name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        scala-version: [ "2.12", "2.13", "3" ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          check-latest: true

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Compile and test
        run: sbt "project root2_12; test"
        if: matrix.scala-version == '2.12'

      - name: Compile and test
        run: sbt "project root; test"
        if: matrix.scala-version == '2.13'

      - name: Compile and test
        run: sbt "project root3; test"
        if: matrix.scala-version == '3'

  ci-passed:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ':'
